colorScheme = "fire"
smartTOC = true

[homepage]
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showTableOfContents = true

[header]
  layout = "fixed"
